local opts = {

	flavour = "mocha",
	background = {
		light = "latte",
		dark = "frappe",
	},
	color_overrides = {
		-- white = {
		-- 	rosewater = "#cc7983",
		-- 	flamingo = "#bb5d60",
		-- 	pink = "#d54597",
		-- 	mauve = "#a65fd5",
		-- 	red = "#b7242f",
		-- 	maroon = "#db3e68",
		-- 	peach = "#e46f2a",
		-- 	yellow = "#bc8705",
		-- 	green = "#1a8e32",
		-- 	teal = "#00a390",
		-- 	sky = "#089ec0",
		-- 	sapphire = "#0ea0a0",
		-- 	blue = "#017bca",
		-- 	lavender = "#8584f7",
		-- 	text = "#444444",
		-- 	subtext1 = "#555555",
		-- 	subtext0 = "#666666",
		-- 	overlay2 = "#777777",
		-- 	overlay1 = "#888888",
		-- 	overlay0 = "#999999",
		-- 	surface2 = "#aaaaaa",
		-- 	surface1 = "#bbbbbb",
		-- 	surface0 = "#cccccc",
		-- 	base = "#ffffff",
		-- 	mantle = "#eeeeee",
		-- 	crust = "#dddddd",
		-- },
		latte = {
			-- custom everforest light hard port
			rosewater = "#a43b35",
			flamingo = "#da3537",
			pink = "#d332a1",
			mauve = "#aa3685",
			red = "#ff3532",
			maroon = "#de3631",
			peach = "#f36c0b",
			yellow = "#bd8800",
			green = "#596600",
			teal = "#287e5e",
			sky = "#52b1c7",
			sapphire = "#3fb4b8",
			blue = "#317da7",
			lavender = "#474155",
			text = "#4d4742",
			subtext1 = "#5b5549",
			subtext0 = "#6d6655",
			overlay2 = "#786d5a",
			overlay1 = "#8c7c62",
			overlay0 = "#a18d66",
			surface2 = "#c9bea5",
			surface1 = "#d8d3ba",
			surface0 = "#e8e2c8",
			base = "#ebe4c8",
			mantle = "#e1dab5",
			crust = "#bdc0a0",
		},
		mocha = {
			rosewater = "#f4a192",
			flamingo = "#e46c6b",
			red = "#e8545e",
			maroon = "#b85664",
			pink = "#d487a8",
			mauve = "#c77492",
			peach = "#e98c57",
			yellow = "#e1b658",
			green = "#98c379",
			teal = "#78a991",
			sky = "#6da888",
			sapphire = "#68a0a5",
			blue = "#66999f",
			lavender = "#7b97a3",
			text = "#ebdbb2",
			subtext1 = "#d5c4a1",
			subtext0 = "#bdae93",
			overlay2 = "#a89984",
			overlay1 = "#928374",
			overlay0 = "#595959",
			surface2 = "#4d4d4d",
			surface1 = "#404040",
			surface0 = "#292929",
			base = "#1d2021",
			mantle = "#191b1c",
			crust = "#141617",
		},
		macchiato = {
			base = "#000000",
			mantle = "#000000",
			crust = "#000000",
		},
	},
	term_colors = true,
	dim_inactive = {
		enabled = true,
		shade = "dark",
		percentage = 0.15,
	},
	styles = {
		comments = { "italic" },
		functions = { "bold" },
		conditionals = { "underline" },
	},
	default_integrations = true,
	integrations = {
		alpha = true,
		ufo = true,
		notify = true,
		illuminate = true,
		neotest = true,
		cmp = true,
		gitsigns = true,
		harpoon = true,
		indent_blankline = {
			enabled = true,
			colored_indent_levels = true,
		},
		lsp_trouble = true,
		mason = true,
		markdown = false,
		mini = { enabled = true },
		native_lsp = {
			enabled = true,
			virtual_text = {
				errors = { "italic" },
				hints = { "italic" },
				warnings = { "italic" },
				information = { "italic" },
				ok = { "italic" },
			},
			underlines = {
				errors = { "undercurl" },
				hints = { "undercurl" },
				warnings = { "undercurl" },
				information = { "undercurl" },
			},
			inlay_hints = { background = true },
		},
		nvimtree = true,
		nvim_surround = true,
		telescope = { enabled = true },
		treesitter = true,
		treesitter_context = true,
		which_key = true,
		barbecue = {
			dim_dirname = true, -- directory name is dimmed by default
			bold_basename = true,
			dim_context = false,
			alt_background = false,
		},
	},
	custom_highlights = function(C)
		return {
			CmpItemKindSnippet = { fg = C.base, bg = C.mauve },
			CmpItemKindKeyword = { fg = C.base, bg = C.red },
			CmpItemKindText = { fg = C.base, bg = C.teal },
			CmpItemKindMethod = { fg = C.base, bg = C.blue },
			CmpItemKindConstructor = { fg = C.base, bg = C.blue },
			CmpItemKindFunction = { fg = C.base, bg = C.blue },
			CmpItemKindFolder = { fg = C.base, bg = C.blue },
			CmpItemKindModule = { fg = C.base, bg = C.blue },
			CmpItemKindConstant = { fg = C.base, bg = C.peach },
			CmpItemKindField = { fg = C.base, bg = C.green },
			CmpItemKindProperty = { fg = C.base, bg = C.green },
			CmpItemKindEnum = { fg = C.base, bg = C.green },
			CmpItemKindUnit = { fg = C.base, bg = C.green },
			CmpItemKindClass = { fg = C.base, bg = C.yellow },
			CmpItemKindVariable = { fg = C.base, bg = C.flamingo },
			CmpItemKindFile = { fg = C.base, bg = C.blue },
			CmpItemKindInterface = { fg = C.base, bg = C.yellow },
			CmpItemKindColor = { fg = C.base, bg = C.red },
			CmpItemKindReference = { fg = C.base, bg = C.red },
			CmpItemKindEnumMember = { fg = C.base, bg = C.red },
			CmpItemKindStruct = { fg = C.base, bg = C.blue },
			CmpItemKindValue = { fg = C.base, bg = C.peach },
			CmpItemKindEvent = { fg = C.base, bg = C.blue },
			CmpItemKindOperator = { fg = C.base, bg = C.blue },
			CmpItemKindTypeParameter = { fg = C.base, bg = C.blue },
			CmpItemKindCopilot = { fg = C.base, bg = C.teal },
		}
	end,
}
return {
	"catppuccin/nvim",
	enabled = true,
	lazy = false,
	priority = 1000,
	name = "catppuccin",
	config = function()
		require("catppuccin").setup(opts)
		vim.cmd.colorscheme("catppuccin")

		require("transparent").toggle(vim.g.transparent_enabled)
	end,
}
